// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_HfoaKX8pRKwT_p_X7jFUHe1aZTxqrrA',
    appId: '1:780052900814:web:279fb6a92e197a5a32d99f',
    messagingSenderId: '780052900814',
    projectId: 'serviceapp-f597a',
    authDomain: 'serviceapp-f597a.firebaseapp.com',
    storageBucket: 'serviceapp-f597a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8jZPsEGsgpf5FSwZXUd0lhIO10cYYWks',
    appId: '1:780052900814:android:f203c3f5d56a341e32d99f',
    messagingSenderId: '780052900814',
    projectId: 'serviceapp-f597a',
    storageBucket: 'serviceapp-f597a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXo5DwRnp0iz1X1xjtJOZYFR0JHyP4dfE',
    appId: '1:780052900814:ios:551376e432e4d73032d99f',
    messagingSenderId: '780052900814',
    projectId: 'serviceapp-f597a',
    storageBucket: 'serviceapp-f597a.firebasestorage.app',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXo5DwRnp0iz1X1xjtJOZYFR0JHyP4dfE',
    appId: '1:780052900814:ios:551376e432e4d73032d99f',
    messagingSenderId: '780052900814',
    projectId: 'serviceapp-f597a',
    storageBucket: 'serviceapp-f597a.firebasestorage.app',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_HfoaKX8pRKwT_p_X7jFUHe1aZTxqrrA',
    appId: '1:780052900814:web:b3f4fa89f7b88ede32d99f',
    messagingSenderId: '780052900814',
    projectId: 'serviceapp-f597a',
    authDomain: 'serviceapp-f597a.firebaseapp.com',
    storageBucket: 'serviceapp-f597a.firebasestorage.app',
  );
}
